### ISSUE TITLE
problem when running gpt_benchmark

### ISSUE THREAD

**Issue by hkz103** [AntCPLab/puma_benchmarks#4]
When I try to run the puma_gpt2_benchmark, how can I handle with this problem? The following is the log output:

INFO: Running command line: bazel-bin/examples/python/ml/puma_gpt2_benchmarks/puma_gpt2_benchmarks
2023-12-23 08:08:29.888486: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Downloading data: 100%|██████████████████████████████████████████████████████████████| 190M/190M [00:36<00:00, 5.18MB/s]
Generating test split: 4358 examples [00:00, 40249.65 examples/s]
Generating train split: 1801350 examples [00:29, 60951.29 examples/s]
Generating validation split: 3760 examples [00:00, 61425.32 examples/s]
Perplexity of 100 wikitext-103-v1 sentences
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/9de4a6aef89daf40df580afb13ff9f9d/execroot/spulib/bazel-out/k8-opt/bin/examples/python/ml/puma_gpt2_benchmarks/puma_gpt2_benchmarks.runfiles/spulib/examples/python/ml/puma_gpt2_benchmarks/puma_gpt2_benchmarks.py", line 197, in <module>
    perplexity_cpu = eval_cpu_perp()
  File "/root/.cache/bazel/_bazel_root/9de4a6aef89daf40df580afb13ff9f9d/execroot/spulib/bazel-out/k8-opt/bin/examples/python/ml/puma_gpt2_benchmarks/puma_gpt2_benchmarks.runfiles/spulib/examples/python/ml/puma_gpt2_benchmarks/puma_gpt2_benchmarks.py", line 185, in eval_cpu_perp
    logits = calculate_logits(pretrained_model.params, ids)
  File "/root/.cache/bazel/_bazel_root/9de4a6aef89daf40df580afb13ff9f9d/execroot/spulib/bazel-out/k8-opt/bin/examples/python/ml/puma_gpt2_benchmarks/puma_gpt2_benchmarks.runfiles/spulib/examples/python/ml/puma_gpt2_benchmarks/puma_gpt2_benchmarks.py", line 136, in calculate_logits
    logits = outputs.logits[:, :-1, :].reshape(batch_num, -1)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/numpy/array_methods.py", line 143, in _reshape
    newshape = _compute_newshape(a, args[0] if len(args) == 1 else args)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/numpy/array_methods.py", line 133, in _compute_newshape
    return tuple(-core.divide_shape_sizes(np.shape(a), newshape)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/numpy/array_methods.py", line 133, in <genexpr>
    return tuple(-core.divide_shape_sizes(np.shape(a), newshape)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/core.py", line 1954, in divide_shape_sizes
    return handler.divide_shape_sizes(ds[:len(s1)], ds[len(s1):])
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/core.py", line 1837, in divide_shape_sizes
    raise InconclusiveDimensionOperation(f"Cannot divide evenly the sizes of shapes {tuple(s1)} and {tuple(s2)}")
jax._src.core.InconclusiveDimensionOperation: Cannot divide evenly the sizes of shapes (1, 8, 50257) and (100, -1)

**Comment by pguihc** [comment]
@hkz103 Hi, has this problem been solved? I encountered the exact same error as you.

**Comment by Ye-D** [comment]
@pguihc @hkz103 sorry for replying late, we do not reshape ops in line https://github.com/AntCPLab/puma_benchmarks/blob/835db68d578038f5f79ce0c8fd2822c7e1599930/puma_gpt2_benchmarks/puma_gpt2_benchmarks.py#L136, del the reshape will work.
